### ISSUE TITLE
Annotating a function with @Debt is not displaying any warning in console logs

### ISSUE THREAD

**Issue by frozenfire699** [Stuie/papercut#16]
After annotating a class/function/variable in Java file with @Debt,  running mvn clean install doesn't generate any warning about tech debt.
POM is updated with both dependencies for compiler and annotations v 0.9.1

**Comment by Stuie** [comment]
Is the compiler configured as an `annotationProcessor`?

Could you share the relevant parts of your POM please?

**Comment by frozenfire699** [comment]
Below is my configuration i added in POM.
```
  <!-- https://mvnrepository.com/artifact/ie.stu/papercut-compiler -->
        <dependency>
            <groupId>ie.stu</groupId>
            <artifactId>papercut-compiler</artifactId>
            <version>0.9.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/ie.stu/papercut-compiler -->
        <dependency>
            <groupId>ie.stu</groupId>
            <artifactId>papercut-annotations</artifactId>
            <version>0.9.1</version>
        </dependency>
```

After playing around, made the following observations
1. WARNING shows up in console logs under  **maven-compiler-plugin** only when the either `description` or `addedDate` properties are used. If i use any other property, console logs are not generated
2.  I was not able to find any link for report/documentation in console logs or my target folder, that can help me track all @Debt annotations in a single place. Using compiler console logs to track tech debt is practically impossible.

**Comment by Stuie** [comment]
I'm not familiar with Maven, but I see that [there are options for specifying annotation processors](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html). Have you tried those?

**Comment by Stuie** [comment]
No response for a year and a half. Closing.
