### ISSUE TITLE
Suggestion: Add option to invert the default behavior 

### ISSUE THREAD

**Issue by rfgamaral** [Stuie/papercut#2]
By default Papercut assumes `stopShip = true` and fails the build if anything is annotated. I suggest to add some kind of global configuration option to invert this behavior. Instead, don't fail the build unless `stopShip = true` is specified.

I understand that such option is opposing the initial idea that probably made you develop this but I see myself taking advantage of such thing if the behavior is inverted.

Just a suggestion :)

#goodjob

**Comment by Stuie** [comment]
Hmm, that's a tough one. The annotation class requires a default value, which I set to true.

When the annotation processor finds the annotation I don't think it can determine if the value was supplied as a default, or specified by the user.

I could add a different annotation that sounds less like a demand, with the desired behavior. Something like "@Refactor" or "\@TechDebt", perhaps.

**Comment by rfgamaral** [comment]
I'm not sure if it works in the same way but https://github.com/rzwitserloot/lombok has many annotations and some options are configurable in a `lombok.config` file. Maybe you could see how they did it?

If not, a different annotation to invert the behavior feels like a solid approach. As for the name I'd personally pick `@Refactor` over `@TechDebt` because the latter is too specific and sometimes I just want to tag something that should be refactored in the future which may eventually become technical debt or not.

**Comment by Stuie** [comment]
I added a `@Refactor` annotation in version 0.0.3. The behavior is identical to `@RemoveThis`, except stopShip is false by default, so you'll only get warnings. You can specify `stopShip = true` if you decide you want your `@Refactor` to fail your build in the future.

**Comment by rfgamaral** [comment]
Awesome. Thanks :)
