### ISSUE TITLE
[Feature Request] TODOs

### ISSUE THREAD

**Issue by vibin** [Stuie/papercut#4]
I have a few use cases where I think a generic annotation like @TODO makes more sense than @RemoveThis or @Refactor.  For example, when I do a release build but forget to change the placeholder strings resources to final ones.

Thanks!

**Comment by StefMa** [comment]
Where is the benefit to use a annotation instead of a comment like 

`//TODO do stuff `

**Comment by vibin** [comment]
I cannot cause a build failure with `// TODO do stuff`.

**Comment by Stuie** [comment]
With the annotation you could choose to fail for certain instances, and not for others.

Perhaps you want to fail for placeholder strings but not for adding javadoc, etc.

Tools like Checkstyle don't have that level of granularity.

**Comment by Stuie** [comment]
@vibinr Can you think of any specific new behavior that you would need for a `@Todo` that you couldn't just do with `@Refactor`? Is it simply a naming issue for you?

I don't want to end up with many annotations with duplicated behavior if I can avoid it. :)

**Comment by vibin** [comment]
I want the build to fail each time I do @TODO with stopShip = true. So, same as @Refactor, including targeted element types, just the name is different.

Don't think I understand Checkstyle's relevance here...

**Comment by vibin** [comment]
@Stuie yeah, it's just a naming thing. "Refactor" just doesn't go right for everything apparently.

**Comment by Stuie** [comment]
@vibinr I was responding more to @StefMa's question 

> Where is the benefit to use a annotation instead of a comment

You can set up Checkstyle to fail a build when it finds a `// TODO` or `// FIXME` comment, but you don't have the same level granularity of control with that, as you may want some of them to fail the build, but not all of them. This is especially the case if you're in a large existing codebase with comments like that in multiple places. An annotation is much more fine-grained.

If you're starting with a brand new codebase then arguably Checkstyle makes more sense.

There was [a thread about this on Reddit](https://www.reddit.com/r/androiddev/comments/5jrk88/tackle_your_tech_debt_with_papercut/dbikcjt/) if you're interested in reading more.

**Comment by vibin** [comment]
@Stuie Yeah, that makes sense. What do you think of entirely replacing @Refactor with @Todo?

**Comment by vibin** [comment]
Got this functionality working with Android lint's StopShip instead 😀
http://stackoverflow.com/questions/33504186/how-to-make-grade-release-build-fail-using-lint-option-stopship

**Comment by Stuie** [comment]
Given that you're happy with your solution, and the feature request is essentially to duplicate/rename an annotation with no new behavior I'm just going to close it for now.

I'll keep a rename in mind, and especially if I get another feature request along the same lines.
