### ISSUE TITLE
Support Java 8

### ISSUE THREAD

**Issue by Wavesonics** [Stuie/papercut#5]
Annotations should support Java 8 to avoid warnings when used in projects that use Java 8

Warning:Supported source version 'RELEASE_7' from annotation processor 'ie.stu.papercut.compiler.AnnotationProcessor' less than -source '1.8'

**Comment by Stuie** [comment]
Papercut contains no Java 1.8 language features, so I need to look into the impact this will have on Android users. I know JDK8 support is very limited there at the moment. 

If updating these values causes build issues for many Android apps then that is a more significant problem than a warning.

I'll look into it and see if I can remove the warning and keep the library working with Android. It may be a very simple change.

**Comment by Stuie** [comment]
@Wavesonics Do you have a project where you're seeing this warning that you can share? It would help me to make sure I'm fixing the issue if I have a simple repro case. If you don't have a project, can you give me some information about the project (specific build configuration, JDK installed, etc.)?

**Comment by Stuie** [comment]
Reading [general advice on the Oracle site](https://blogs.oracle.com/darcy/entry/jdk_6_build_101_jsr) gives me a place to begin.

**Comment by Stuie** [comment]
Flat out removing the compatibility lines from the library results in a test Android project not working.

```
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```

**Comment by Stuie** [comment]
I can't find a way to compile without setting the compatibility to 1.7 and still have it work in my test Android project. I think this will have to wait until adoption of the [Jack compiler](https://developer.android.com/guide/platform/j8-jack.html) is nearly ubiquitous.

Resolving for now. Please re-open if you have advice on how I can achieve this.

**Comment by madisp** [comment]
Note that the problem/warning is not about

```
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```

but rather this line:

https://github.com/Stuie/papercut/blob/master/papercut-compiler/src/main/java/ie/stu/papercut/compiler/AnnotationProcessor.java#L39

your annotation processor should probably support `SourceVersion.RELEASE_8`

**Comment by Stuie** [comment]
Ah, I see now. That should be a trivial change then.

Apologies for the confusion.

**Comment by Stuie** [comment]
Just pushed version 0.0.4 with the relevant change.
