### ISSUE TITLE
Find @Refactor and @RemoveThis 

### ISSUE THREAD

**Issue by MrVilkaman** [Stuie/papercut#7]
I need something for find all code that need refactoring or delete. How I can do this?
Maybe you will do integration with TODO plugin? Or create new way for find  @Refactor and @RemoveThis.

Something like this:
![img](http://i.prntscr.com/6f2de5904b84487a81ccb3c7d4a8abb5.png)

**Comment by Stuie** [comment]
The only way to find all `@Refactor` or `@RemoveThis` annotations is in the build output, or by using search tools in your IDE. If you don't set due dates on your `@Refactor` annotations you'll see them all as warnings in your build output.

I originally only intended Papercut to warn you about tech debt that was past its due date. I've had a few pieces of feedback that suggest it would be useful to be able to generate a report. Issue #6 mentions a PMD plugin, and feedback on Reddit suggested FindBugs/Checkstyle report integration.

Some integration with IDEs would be great, but there are many IDEs, and writing plugins for them adds an extra installation step for all users.

I will use this as the tracking issue for my initial investigation into the above.

**Comment by Stuie** [comment]
I was just looking into this as part of a rewrite of Papercut, and it turns out that [IntelliJ lets you specify patterns](https://www.jetbrains.com/help/idea/using-todo.html#add_pattern_filter_todo) for things that are considered "To do".
